@startuml



class User{
    name: string
    user_id: int
    login_id: string
    password: string

    }



class Project{
    title: string
    prj_id: int
    overview: string
    host_id: int
    deadline: datatime
    status: int
    isDelayed: boolean
}

class Task{
    title: string
    task_id: int
    overview: string
    deadline: datatime
    status: int
    isDelayed: boolean
    staff_id_list: list

}


class Join_Prj{
    user_id: int
    prj_id: int
    isOwn: boolean
}

class Join_Tsk{
    user_id: int
    task_id: int
    isStaff: boolean

}

Project "1"--"0..*" Task:▼従属
User "1"--"0..*" Join_Prj:▼参加
User "1"--"0..*" Join_Tsk:▼参加
Join_Prj"1..*"--"1" Project:参照
Join_Tsk"1..*"--"1" Task:参照




@enduml